site_name: eFleetPlan Documentation
site_description: Co-optimisation tool of charging infrastructure investment and electric fleet operations.
site_author: Carolina Gil Ribeiro
site_url: https://mcarolinagilr.github.io/eFleetPlan
repo_url: https://github.com/mcarolinagilr/eFleetPlan
repo_name: mcarolinagilr/eFleetPlan

theme:
  name: material
  font:
    text: "Arial"
    code: "Roboto Mono"
  language: en
  features:
    - navigation.sections
    - navigation.instant
    - navigation.top
    - navigation.expand
    - content.code.copy
    - toc.integrate
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - tables

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: true

nav:
  - "Home": index.md
  - "0. Getting started": getting-started.md
  - "1. User guide": 
      - "1.1. Overview": user-guide/overview.md
      - "1.2. Package 1 - Fleet operation simulation": user-guide/package1.md
      - "1.3. Package 2 - Co-optimisation": user-guide/package2.md
  - "2. Configuration settings":
      - "2.1. Environment": configuration/environment.md
      - "2.2. Fleet Operation simulation": configuration/fleetoperation_simulation.md
      - "2.3. Co-optimisation": configuration/Co-optimisation.md
      - "2.4. Predefined parameters": configuration/predefined.md
  - "3. Software functionalities":
      - "3.1. Config Loaders": api/config-loaders.md
      - "3.2. Fleet operation modelling": api/fleetoperation_modelling.md
      - "3.3. Co-optimisation": api/Co-optimisation.md
      - "3.4. Visualisation": api/visualisation.md
  - "4. Examples & Tutorials": examples.md

extra_css:
  - stylesheets/extra.css